(cl:defpackage stag_ros-srv
  (:use )
  (:export
   "SETTRACKEDBUNDLES"
   "<SETTRACKEDBUNDLES-REQUEST>"
   "SETTRACKEDBUNDLES-REQUEST"
   "<SETTRACKEDBUNDLES-RESPONSE>"
   "SETTRACKEDBUNDLES-RESPONSE"
  ))

