// Generated by gencpp from file stag_ros/SetTrackedBundlesResponse.msg
// DO NOT EDIT!


#ifndef STAG_ROS_MESSAGE_SETTRACKEDBUNDLESRESPONSE_H
#define STAG_ROS_MESSAGE_SETTRACKEDBUNDLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stag_ros
{
template <class ContainerAllocator>
struct SetTrackedBundlesResponse_
{
  typedef SetTrackedBundlesResponse_<ContainerAllocator> Type;

  SetTrackedBundlesResponse_()
    : success(false)  {
    }
  SetTrackedBundlesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTrackedBundlesResponse_

typedef ::stag_ros::SetTrackedBundlesResponse_<std::allocator<void> > SetTrackedBundlesResponse;

typedef boost::shared_ptr< ::stag_ros::SetTrackedBundlesResponse > SetTrackedBundlesResponsePtr;
typedef boost::shared_ptr< ::stag_ros::SetTrackedBundlesResponse const> SetTrackedBundlesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator1> & lhs, const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator1> & lhs, const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stag_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stag_ros/SetTrackedBundlesResponse";
  }

  static const char* value(const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTrackedBundlesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stag_ros::SetTrackedBundlesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAG_ROS_MESSAGE_SETTRACKEDBUNDLESRESPONSE_H
