// Generated by gencpp from file stag_ros/StagMarkers.msg
// DO NOT EDIT!


#ifndef STAG_ROS_MESSAGE_STAGMARKERS_H
#define STAG_ROS_MESSAGE_STAGMARKERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stag_ros/StagMarker.h>

namespace stag_ros
{
template <class ContainerAllocator>
struct StagMarkers_
{
  typedef StagMarkers_<ContainerAllocator> Type;

  StagMarkers_()
    : header()
    , markers()  {
    }
  StagMarkers_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::stag_ros::StagMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::stag_ros::StagMarker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::stag_ros::StagMarkers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stag_ros::StagMarkers_<ContainerAllocator> const> ConstPtr;

}; // struct StagMarkers_

typedef ::stag_ros::StagMarkers_<std::allocator<void> > StagMarkers;

typedef boost::shared_ptr< ::stag_ros::StagMarkers > StagMarkersPtr;
typedef boost::shared_ptr< ::stag_ros::StagMarkers const> StagMarkersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stag_ros::StagMarkers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stag_ros::StagMarkers_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stag_ros::StagMarkers_<ContainerAllocator1> & lhs, const ::stag_ros::StagMarkers_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.markers == rhs.markers;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stag_ros::StagMarkers_<ContainerAllocator1> & lhs, const ::stag_ros::StagMarkers_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stag_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::StagMarkers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stag_ros::StagMarkers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::StagMarkers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stag_ros::StagMarkers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::StagMarkers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stag_ros::StagMarkers_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stag_ros::StagMarkers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "651766ef07e9246eea9b89a8695f7aa1";
  }

  static const char* value(const ::stag_ros::StagMarkers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x651766ef07e9246eULL;
  static const uint64_t static_value2 = 0xea9b89a8695f7aa1ULL;
};

template<class ContainerAllocator>
struct DataType< ::stag_ros::StagMarkers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stag_ros/StagMarkers";
  }

  static const char* value(const ::stag_ros::StagMarkers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stag_ros::StagMarkers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header    \n"
"StagMarker[] markers    \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stag_ros/StagMarker\n"
"Header header\n"
"uint32 id\n"
"float32 reprojection_error # sum of the squared reprojection error of each corner\n"
"geometry_msgs/PoseStamped pose # pose from solvePnP\n"
"geometry_msgs/Point[] corners # corners from marker detection in image coordinates\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::stag_ros::StagMarkers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stag_ros::StagMarkers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StagMarkers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stag_ros::StagMarkers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stag_ros::StagMarkers_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::stag_ros::StagMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAG_ROS_MESSAGE_STAGMARKERS_H
